### ISSUE TITLE
Povoar o BD

### ISSUE THREAD

**Issue by viniciuslacerda0** [viniciuslacerda0/projetoBD#1]
Colocar um moi de coisa ai dentro

**Comment by KelvinCL** [comment]
--Cliente

INSERT INTO CLIENTE
VALUES('00000000000','a.ufcg.edu.br','Alessandra', 'Rua Desembargador Trindade', 'F', '08/19/1977');

INSERT INTO CLIENTE
VALUES('00000000001','j.ufcg.edu.br','Joana Machado', 'Rua João XXIII', 'F', '03/05/1981');

INSERT INTO CLIENTE
VALUES('00000000003','c.ufcg.edu.br','Cirilo Quirino', 'Rua Augusto', 'M', '09/05/2000');


INSERT INTO CLIENTE
VALUES('00000000004','f.ufcg.edu.br','Francisca Renata dos Santos', 'Avenida Diogo Feijó', 'F', '06/23/1998');

INSERT INTO CLIENTE
VALUES('00000000005','q.ufcg.edu.br','Quenia dos Anjos', 'Avenida Marechal Deodoro', 'F', '04/23/1993');

INSERT INTO CLIENTE
VALUES('00000000006','t.ufcg.edu.br','Tania Albuquerque de Queiroz', 'Rua da Boêmia', 'F', '08/23/1983');



INSERT INTO CLIENTE
VALUES('00000000007','jb.ufcg.edu.br','José Bonifácio', 'Rua Sem Nome', 'M', '08/23/1949');



INSERT INTO CLIENTE
VALUES('00000000008','jp.ufcg.edu.br','João Pedro', 'Rua Sem Nome', 'M', '08/29/1999');



INSERT INTO CLIENTE
VALUES('00000000009','ra.ufcg.edu.br','Rânia Almeida', 'Rua da Penha', 'F', '08/29/1999');



INSERT INTO CLIENTE
VALUES('00000000010','ma.ufcg.edu.br','Marileidy Andréia', 'Rua Quebra-quilos', 'F', '08/29/1982');



INSERT INTO CLIENTE
VALUES('00000000011','ss.ufcg.edu.br','Santana da Silva', 'Rua Padre Antônio', 'M', '08/29/1963');




INSERT INTO CLIENTE
VALUES('00000000012','sis.ufcg.edu.br','Silmara Santos', 'Rua Padre Antônio', 'F', '08/30/1989');



INSERT INTO CLIENTE
VALUES('00000000013','lil.ufcg.edu.br','Luís Inácio Loiola', 'Rua Padre Antônio', 'M', '12/17/1959');



INSERT INTO CLIENTE
VALUES('00000000014','jq.ufcg.edu.br','Jânio Quadros', 'Rua Padre Antônio', 'M', '12/17/1957');


--Dependente



INSERT INTO DEPENDENTE
VALUES('00000000015','10/11/2000','Jânio Quadros','00000000006' );


INSERT INTO DEPENDENTE
VALUES('00000000016','10/11/2000','Pedro Quadros','00000000006' );



INSERT INTO DEPENDENTE
VALUES('00000000017','10/11/1977','Ana Beatriz','00000000007' );



INSERT INTO DEPENDENTE
VALUES('00000000018','10/11/1977','Ana Paula','00000000008' );



INSERT INTO DEPENDENTE
VALUES('00000000019','01/07/1989','Pedro de Almeida','00000000008' );


INSERT INTO DEPENDENTE
VALUES('00000000020','01/07/1995','Larissa Nadja','00000000008' );


INSERT INTO DEPENDENTE
VALUES('00000000021','03/08/1995','Jasmin Nakagawa','00000000008' );




INSERT INTO DEPENDENTE
VALUES('00000000022','05/09/1987','Matheus Júlio','00000000011' );



INSERT INTO DEPENDENTE
VALUES('00000000023','09/14/1968','Vânia Lara','00000000011' );


INSERT INTO DEPENDENTE
VALUES('00000000024','09/17/1975','Pedro Rocha','00000000011' );



INSERT INTO DEPENDENTE
VALUES('00000000025','04/26/1986','Humberto Carlos','00000000003' );

**Comment by KelvinCL** [comment]
INSERT INTO DEPENDENTE
VALUES('00000000026','04/26/1987','Maria Joana','00000000003' );


INSERT INTO DEPENDENTE
VALUES('00000000027','09/17/1975','Maria Joaquina','00000000011' );

INSERT INTO DEPENDENTE
VALUES('00000000028','09/29/1969','Carla Maria','00000000011' );


INSERT INTO DEPENDENTE
VALUES('00000000029','03/08/1995','Jonábia Maria Ágatha','00000000008' );

-- Funcionario


INSERT INTO FUNCIONARIO
VALUES('00000000027','Maria da Penha','06/23/1954',3000,'Gerente' );



INSERT INTO FUNCIONARIO
VALUES('00000000028','João da Penha','06/23/1954',3000,'Gerente' );


INSERT INTO FUNCIONARIO
VALUES('00000000029','Evaristo de Macedo','06/23/1948',2000,'Cozinheiro' );


INSERT INTO FUNCIONARIO
VALUES('00000000030','Muricy Ramalho','02/17/1960',2000,'Pintor' );

INSERT INTO FUNCIONARIO
VALUES('00000000032','Guilherme Loureiro','02/19/1970',5000,'Gerente de negócios' );

INSERT INTO FUNCIONARIO
VALUES('00000000033','François Descartes','02/19/1970',3500,'Chef' );

INSERT INTO FUNCIONARIO
VALUES('00000000036','Samuel Etoo','02/19/1979',9000,'Gerente Geral' );

INSERT INTO FUNCIONARIO
VALUES('00000000037','Joana do Rosário','02/19/1985',1000,'Estagiária' );

INSERT INTO FUNCIONARIO
VALUES('00000000038','Carlos Consorti','01/01/1985',1000,'Estagiário' );

INSERT INTO FUNCIONARIO
VALUES('00000000039','Jonas Landucci','01/01/1990',3500,'Segurança' );

INSERT INTO FUNCIONARIO
VALUES('00000000040','Joey Bane','01/08/1973',3500,'Segurança' );

INSERT INTO FUNCIONARIO
VALUES('00000000041','Mario Kempes','03/01/1969',3500,'Segurança' );

INSERT INTO FUNCIONARIO
VALUES('00000000042','Rosali Silva','09/19/1975',3500,'Guia' );

-- Quarto

INSERT INTO QUARTO
VALUES('A-999','Duplo','Lateral - mar',3500);

INSERT INTO QUARTO
VALUES('B-999','Duplo Casal','Lateral - mar',3500);

INSERT INTO QUARTO
VALUES('C-999','Triplo','Frente - mar',9500);

INSERT INTO QUARTO
VALUES('A-100','SIMPLES','Sem',500);

INSERT INTO QUARTO
VALUES('A-105','SIMPLES','Lateral - mar',1000);

INSERT INTO RESERVA
VALUES(1,'00000000001', 'A-105', '03/10/2018', '03/11/2018');

INSERT INTO RESERVA
VALUES(2,'00000000001', 'A-105', '03/20/2018', '03/21/2018');

INSERT INTO RESERVA
VALUES(3,'00000000012', 'C-999', '09/15/2019', '10/18/2019');

INSERT INTO RESERVA
VALUES(4,'00000000011', 'B-999', '06/24/2019', '06/25/2019');

INSERT INTO RESERVA
VALUES(5,'00000000013', 'B-999', '06/24/2019', '06/25/2019');

INSERT INTO RESERVA
VALUES(6,'00000000013', 'B-999', '06/29/2019', '06/30/2019');

INSERT INTO RESERVA
VALUES(7,'00000000014', 'A-100', '08/07/2019', '08/08/2019');

INSERT INTO RESERVA
VALUES(8,'00000000014', 'B-999', '08/11/2019', '08/12/2019');

INSERT INTO RESERVA
VALUES(9,'00000000014', 'B-999', '08/13/2019', '08/14/2019');

INSERT INTO RESERVA
VALUES(10,'00000000014', 'C-999', '10/10/2019', '08/15/2019');

**Comment by KelvinCL** [comment]
--PRODUTO

INSERT INTO PRODUTO
VALUES(1, 'ALIMENTICIO', 'LEITE', 3.00, 'LEITE EM PÓ');

INSERT INTO PRODUTO
VALUES(2, 'ALIMENTICIO', 'BOLACHA CREAM CRACKER VITARELLA', 3.50, 'DERRETE NA BOCA');

INSERT INTO PRODUTO
VALUES(3, 'ALIMENTICIO', 'ACHOCOLATADO NESCAU', 5.58, 'ENERGIA QUE DÁ GOSTO');

INSERT INTO PRODUTO
VALUES(4, 'ALIMENTICIO', 'CAPPUCCINO', 8.95, 'FÁCIL DE FAZER');

INSERT INTO PRODUTO
VALUES(5, 'ALIMENTICIO', 'CHÁ EM SACHÊ', 1.95, 'SABOR ERVA DOCE');

INSERT INTO PRODUTO
VALUES(6, 'LIMPEZA', 'DETERGENTE', 1.70, 'NEUTRO');

INSERT INTO PRODUTO
VALUES(7, 'LIMPEZA', 'DESINFETANTE', 3.30, 'Fragrância LAVANDA');

INSERT INTO PRODUTO
VALUES(8, 'MOBÍLIA', 'CAMA', 50, 'MADEIRA MOGNO');

INSERT INTO PRODUTO
VALUES(9, 'MOBÍLIA', 'COLCHAO', 20, 'DE MOLAS');

INSERT INTO PRODUTO
VALUES(10, 'MOBÍLIA', 'BANQUINHO', 10, 'DE MADEIRA');

INSERT INTO PRODUTO
VALUES(11, 'ALIMENTICIO', 'PAO', 2.00, 'FRANCES');

INSERT INTO PRODUTO
VALUES(12, 'ALIMENTICIO', 'PAO DOCE', 2.00, 'DE COCO');

INSERT INTO PRODUTO
VALUES(13, 'ALIMENTICIO', 'CHOCOLATE', 7.00, 'AO LEITE');

INSERT INTO PRODUTO
VALUES(14, 'ALIMENTICIO', 'ABACAXI', 3.00, 'MADURO');

INSERT INTO PRODUTO
VALUES(15, 'ALIMENTICIO', 'MELAO', 3.00, 'JAPONES');

**Comment by KelvinCL** [comment]
--HOSPEDA

INSERT INTO HOSPEDA
VALUES(1, '08/07/2019','08/08/2019', '00000000014','A-100');

INSERT INTO HOSPEDA
VALUES(2, '03/10/2018','03/11/2018', '00000000001','A-105');

INSERT INTO HOSPEDA
VALUES(3, '06/29/2019','06/30/2019', '00000000013','B-999');

INSERT INTO HOSPEDA
VALUES(4, '10/10/2019','08/15/2019', '00000000014','C-999');

INSERT INTO HOSPEDA
VALUES(5, '08/13/2019','08/14/2019', '00000000014','B-999');

INSERT INTO HOSPEDA
VALUES(6, '03/20/2018','03/21/2018', '00000000001','A-105');

INSERT INTO HOSPEDA
VALUES(7, '08/11/2019','08/12/2019', '00000000014','B-999');


INSERT INTO HOSPEDA
VALUES(8, '09/15/2019','10/18/2019', '00000000012','C-999');

INSERT INTO HOSPEDA
VALUES(9, '06/24/2019','06/25/2019', '00000000011','B-999');

INSERT INTO HOSPEDA
VALUES(10, '06/24/2019','06/25/2019', '00000000013','B-999');

**Comment by viniciuslacerda0** [comment]
Adicionado ao arquivo inserts.sql

**Comment by KelvinCL** [comment]
INSERT INTO VENDA
VALUES(1, 13,'C-999', '08/11/2019', 10);

INSERT INTO VENDA
VALUES(2, 11,'C-999', '08/11/2019', 10);

INSERT INTO VENDA
VALUES(3, 11,'C-999', '08/11/2019', 10);

INSERT INTO VENDA
VALUES(4, 2,'C-999', '08/11/2019', 2);

INSERT INTO VENDA
VALUES(5, 2,'A-105', '03/10/2018', 2);

INSERT INTO VENDA
VALUES(6, 14,'A-105', '06/29/2019', 1);

**Comment by KelvinCL** [comment]
INSERT INTO MANUTENCAO
VALUES(1, '00000000031', 'A-999', '03-10-2019', 'qq','sem');

INSERT INTO MANUTENCAO
VALUES(2, '00000000031', 'B-999', '03-11-2019', 'qq','sem');

INSERT INTO MANUTENCAO
VALUES(3, '00000000031', 'A-100', '03-12-2019', 'qq','sem');

INSERT INTO MANUTENCAO
VALUES(4, '00000000031', 'B-999', '03-13-2019', 'qq','sem');

INSERT INTO MANUTENCAO
VALUES(5, '00000000031', 'A-105', '03-13-2019', 'qq','sem');

INSERT INTO MANUTENCAO
VALUES(6, '00000000038', 'C-999', '03-13-2019', 'qq','sem');

INSERT INTO MANUTENCAO
VALUES(7, '00000000038', 'A-105', '03-20-2019', 'qq','sem');

INSERT INTO MANUTENCAO
VALUES(8, '00000000037', 'A-105', '03-21-2019', 'qq','sem');

INSERT INTO MANUTENCAO
VALUES(9, '00000000037', 'A-100', '03-21-2019', 'qq','sem');

INSERT INTO MANUTENCAO
VALUES(10, '00000000037', 'B-999', '03-22-2019', 'qq','sem');


INSERT INTO MANUTENCAO
VALUES(11, '00000000031', 'A-105', '03-12-2019', 'qq','sem');


INSERT INTO MANUTENCAO
VALUES(12, '00000000031', 'C-999', '03-12-2019', 'qq','sem');

**Comment by KelvinCL** [comment]
INSERT INTO MANUTENCAO
VALUES(13, '00000000037', 'C-999', '03-12-2019', 'qq','sem');


INSERT INTO MANUTENCAO
VALUES(14, '00000000037', 'A-999', '03-12-2019', 'qq','sem');



INSERT INTO QUARTO
VALUES('A-106','SIMPLES','Lateral - mar',1000);

INSERT INTO QUARTO
VALUES('A-108','SIMPLES','Lateral - mar',1000);

INSERT INTO MANUTENCAO
VALUES(15, '00000000037', 'A-106', '03-12-2019', 'qq','sem');


INSERT INTO MANUTENCAO
VALUES(16, '00000000033', 'A-107', '03-12-2019', 'qq','sem');

INSERT INTO MANUTENCAO
VALUES(17, '00000000033', 'A-105', '03-21-2019', 'qq','sem');

INSERT INTO MANUTENCAO
VALUES(18, '00000000033', 'A-100', '03-21-2019', 'qq','sem');

INSERT INTO MANUTENCAO
VALUES(19, '00000000033', 'B-999', '03-22-2019', 'qq','sem');



INSERT INTO MANUTENCAO
VALUES(20, '00000000033', 'C-999', '03-22-2019', 'qq','sem');

INSERT INTO MANUTENCAO
VALUES(21, '00000000033', 'A-107', '03-23-2019', 'qq','sem');
